# Étape 1 : Construire l'application Angular
FROM node:22.11.0-alpine3.20 as build

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances Angular
RUN npm ci

# Copier tous les fichiers du projet Angular dans le conteneur
COPY . .

# Construire l'application pour production
RUN npm run build --prod

# Étape 2 : Créer une image NGINX pour servir l'application
FROM nginx:alpine

# Copier les fichiers générés du build Angular dans le dossier de l'image NGINX
COPY --from=build /app/dist/tp-foyer-frontend /usr/share/nginx/html

# Exposer le port 80 pour le serveur NGINX
EXPOSE 80

# Lancer le serveur NGINX
CMD ["nginx", "-g", "daemon off;"]
